#!/bin/bash

clean_up() {
  cat <<EOS | mysql -uroot -ppass
DROP DATABASE IF EXISTS test_kisakone;
EOS
  rm -f /kisakone_local/config.php
}

sync() {
  [[ ! -d /kisakone ]] && echo "error: /kisakone not found" && exit 1
  mkdir -p /kisakone_local
  rsync -a --delete --exclude=.git --exclude=config.php --exclude=Smarty/templates_c /kisakone/ /kisakone_local/
  cp /vagrant/files/config_site.php /kisakone_local/config_site.php
  chown -R www-data:www-data /kisakone_local
}

debug() {
  # echo "debug: $*"
  :
}


debug "$0 $@"
while [[ $1 ]]; do
  case $1 in
    --clean) clean_up ;;
    *) TESTS="$TESTS $1" ;;
  esac
  shift
done

sync
cd /vagrant/tests
debug "TEST = $TESTS"
if [[ $TESTS ]]; then
  for TEST in $TESTS; do
    debug "Running $TEST"
    /root/nightwatch/bin/nightwatch -c nightwatch-settings.json -g $TEST
  done
else
  debug "Running all tests"
  clean_up
  /root/nightwatch/bin/nightwatch -c nightwatch-settings.json
fi
