#!/bin/bash

clean_up() {
  cat <<EOS | mysql -u root --password=pass
drop database if exists test_kisakone;
EOS
  rm -f /kisakone_local/config.php
}

sync() {
  [[ ! -d /kisakone ]] && echo "error: /kisakone not found" && exit 1
  mkdir -p /kisakone_local
  rsync -a --delete --exclude=.git --exclude=config.php --exclude=Smarty/templates_c /kisakone/ /kisakone_local/
  cp /kisakone_local/config_site.php.example /kisakone_local/config_site.php
  chown -R www-data:www-data /kisakone_local
}

debug() {
  # echo "debug: $*"
  :
}


debug "$0 $@"
while [[ $1 ]]; do
  case $1 in
    --clean) shift; clean_up ;;
    *) break ;;
  esac
done

sync
cd /vagrant/tests
debug "TEST = $1"
if [[ $1 ]]; then
  for TEST in $@; do
    debug "Running $TEST"
    /root/nightwatch/bin/nightwatch -c nightwatch-settings.json -g $TEST
  done
else
  debug "Running all"
  clean_up
  /root/nightwatch/bin/nightwatch -c nightwatch-settings.json
fi
